# Generated by Django 4.0.6 on 2022-07-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Email_Id', models.CharField(max_length=50)),
                ('Department_Name', models.CharField(max_length=50)),
                ('Section_Name', models.CharField(max_length=26)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Roll_Number', models.CharField(max_length=100)),
            ],
        ),
    ]
